@startuml
'https://plantuml.com/sequence-diagram

interface Board{
    - positions: Position[]
    + isEmpty(Position positions)

}

ChessBoard ..|> Board
ChessBoard o-- Position
class ChessBoard{
    - positions: Position[64]
}

Position *-u- Board
Position o-- Piece
class Position{
    - verticalPosition: String
    - horizontalPosition: Integer
    - piece: Piece
    + isEmpty()
    + getVerticalPosition()
    + getHorizontalPosition()
    + getPiece()
}

Piece --> Color
Piece --> PieceType
class Piece{
    - id: Integer
    - pieceType: PieceType
    - color: Color
    + getId()
    + getType()
    + getColor()
}

enum Color{
    - White
    - Black
}

enum PieceType{
    - King
    - Queen
    - Bishop
    - Knight
    - Rook
    - Pawn
    - Invalid
}

Game *-- victoryValidation
Game *-- checkValidation
Game *-- movementValidation
Game *-- Piece
Game *-- Board
class Game{
    - board: Board
    - victoryValidation: VictoryValidation
    - checkValidation: CheckValidation
    - movementValidation: MovementValidation
    - player1Pieces: Piece[]
    - player2Pieces: Piece[]
    - turn: boolean
    + movePiece(piece: Piece, board: Board)
    + promotePawn(pawn: Piece)
    + attackPiece()
}

interface victoryValidation{
    -validateVictory
}

interface checkValidation{
    -validateCheck
}

interface movementValidation{
    -validateMove
}

Move --> Position
class Move{
    -initialPosition: Position
    -finalPosition: Position
}



/'
    --|> herencia
    *-- composición
    o-- agregación
    --> asosiación
    ..> dependencia
    <|.. realización/implementación
'/
@enduml